Adding main Dockerfiles for SV tools
populationgenomics/sv-workflows pull request #5
Opened 2021-03-08 08:58 UTC by pdiakumis

2021-04-19 12:52 UTC, pdiakumis commented
Initially set out to have our own Docker images on Google Artifact Registry in the australia-southeast1 region, but seems that Cromwell doesn't support this registry. Have now reverted to Google Container Registry (in the US region). Not sure what the drawbacks (in a GCP world) would be if we simply used biocontainers from https://quay.io/ (automatically released via the bioconda build process), or if it's simply cheaper to host our own.

2021-04-19 23:33 UTC, pdiakumis commented
@lgruen I've been thinking about this a bit more. I don't think we need to keep the Dockerfiles around for the main tools that already have images built and available on Quay e.g.
- Delly: https://quay.io/repository/biocontainers/delly?tab=tags
- Manta: https://quay.io/repository/biocontainers/manta?tab=tags
- wham: https://quay.io/repository/biocontainers/wham?tab=tags

We can simply copy the latest tags over to `us.gcr.io` with `docker pull` and `docker push`, and we don't even need to worry about builds/GitHub Actions. What do you think?

I'll keep the Melt Dockerfile + build script since it's not available publicly and will put the tarball in a private bucket for us.

2021-04-19 23:46 UTC, lgruen commented
> @lgruen I've been thinking about this a bit more. I don't think we need to keep the Dockerfiles around for the main tools that already have images built and available on Quay e.g.
> 
> * Delly: https://quay.io/repository/biocontainers/delly?tab=tags
> * Manta: https://quay.io/repository/biocontainers/manta?tab=tags
> * wham: https://quay.io/repository/biocontainers/wham?tab=tags
> 
> We can simply copy the latest tags over to `us.gcr.io` with `docker pull` and `docker push`, and we don't even need to worry about builds/GitHub Actions. What do you think?
> 
> I'll keep the Melt Dockerfile + build script since it's not available publicly and will put the tarball in a private bucket for us.

Sounds like a good plan! Copying the images would still be good, so we're isolated from any issues on Quay. It might also be a little faster to download images if we stay within GCP.

2021-04-27 05:10 UTC, pdiakumis commented on dockerfiles/.gitignore
> +melt/MELTv2.2.2.tar.gz
@lgruen done - I've created a new bucket `cpg-sv-workflows` in my dev account.

2021-04-27 05:12 UTC, pdiakumis commented
@lgruen I've cleaned out everything apart from the MELT docker build files. `docker push` instead of `gcloud builds submit` works fine - the latter requires the relevant cloudbuild service account to be given `storage.buckets.get` permissions.

2021-04-27 08:01 UTC, lgruen requested changes

2021-04-27 08:01 UTC, lgruen commented on dockerfiles/.gitignore
> +melt/MELTv2.2.2.tar.gz
Would a bucket in `cpg-common` (potentially even `cpg-reference`) be more appropriate? We should avoid dependencies from our production workflows to dev projects.

2021-04-27 09:03 UTC, pdiakumis commented on dockerfiles/.gitignore
> +melt/MELTv2.2.2.tar.gz
Sure, agreed! I don't have permissions to create that though, so let me know and we can add service account permissions.

2021-05-02 04:13 UTC, closed without merging